export const NOW_PLAYING_MOVIES = {
  dates: {
    maximum: "2024-05-01",
    minimum: "2024-03-20",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
      genre_ids: [28, 27, 53],
      id: 1096197,
      original_language: "en",
      original_title: "No Way Up",
      overview:
        "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
      popularity: 2768.363,
      poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
      release_date: "2024-01-18",
      title: "No Way Up",
      video: false,
      vote_average: 6.504,
      vote_count: 484,
    },
    {
      adult: false,
      backdrop_path: "/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg",
      genre_ids: [878, 28, 18, 12],
      id: 934632,
      original_language: "en",
      original_title: "Rebel Moon — Part Two: The Scargiver",
      overview:
        "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
      popularity: 2477.048,
      poster_path: "/cxevDYdeFkiixRShbObdwAHBZry.jpg",
      release_date: "2024-04-19",
      title: "Rebel Moon — Part Two: The Scargiver",
      video: false,
      vote_average: 6.137,
      vote_count: 552,
    },
    {
      adult: false,
      backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
      genre_ids: [28, 878, 12],
      id: 823464,
      original_language: "en",
      original_title: "Godzilla x Kong: The New Empire",
      overview:
        "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
      popularity: 2372.572,
      poster_path: "/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg",
      release_date: "2024-03-27",
      title: "Godzilla x Kong: The New Empire",
      video: false,
      vote_average: 6.644,
      vote_count: 799,
    },
    {
      adult: false,
      backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
      popularity: 2020.311,
      poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
      release_date: "2024-03-02",
      title: "Kung Fu Panda 4",
      video: false,
      vote_average: 7.16,
      vote_count: 1385,
    },
    {
      adult: false,
      backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
      genre_ids: [878, 12],
      id: 693134,
      original_language: "en",
      original_title: "Dune: Part Two",
      overview:
        "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
      popularity: 1990.512,
      poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      release_date: "2024-02-27",
      title: "Dune: Part Two",
      video: false,
      vote_average: 8.263,
      vote_count: 3456,
    },
    {
      adult: false,
      backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: "en",
      original_title: "Immaculate",
      overview:
        "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
      popularity: 1542.821,
      poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
      release_date: "2024-03-20",
      title: "Immaculate",
      video: false,
      vote_average: 6.252,
      vote_count: 315,
    },
    {
      adult: false,
      backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
      genre_ids: [18, 12],
      id: 618588,
      original_language: "en",
      original_title: "Arthur the King",
      overview:
        "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
      popularity: 1308.397,
      poster_path: "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
      release_date: "2024-03-15",
      title: "Arthur the King",
      video: false,
      vote_average: 6.707,
      vote_count: 70,
    },
    {
      adult: false,
      backdrop_path: "/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg",
      genre_ids: [28, 80, 53],
      id: 1105407,
      original_language: "en",
      original_title: "Damaged",
      overview:
        "A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.",
      popularity: 1263.252,
      poster_path: "/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg",
      release_date: "2024-04-12",
      title: "Damaged",
      video: false,
      vote_average: 4.9,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
      genre_ids: [28, 14],
      id: 634492,
      original_language: "en",
      original_title: "Madame Web",
      overview:
        "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
      popularity: 947.606,
      poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
      release_date: "2024-02-14",
      title: "Madame Web",
      video: false,
      vote_average: 5.616,
      vote_count: 1162,
    },
    {
      adult: false,
      backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 929.948,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.52,
      vote_count: 1252,
    },
    {
      adult: false,
      backdrop_path: "/unCdljyU2FuUBDUcdZezeI9yaaj.jpg",
      genre_ids: [878, 9648, 53],
      id: 720321,
      original_language: "en",
      original_title: "Breathe",
      overview:
        "Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.",
      popularity: 827.058,
      poster_path: "/gPAW0a24TrkafrJQ1axEv0I3jov.jpg",
      release_date: "2024-04-04",
      title: "Breathe",
      video: false,
      vote_average: 5.042,
      vote_count: 60,
    },
    {
      adult: false,
      backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
      genre_ids: [28, 53],
      id: 984324,
      original_language: "fr",
      original_title: "Le salaire de la peur",
      overview:
        "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
      popularity: 811.937,
      poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
      release_date: "2024-03-28",
      title: "The Wages of Fear",
      video: false,
      vote_average: 5.7,
      vote_count: 202,
    },
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
      popularity: 810.306,
      poster_path: "/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
      release_date: "2024-03-19",
      title: "Late Night with the Devil",
      video: false,
      vote_average: 7.306,
      vote_count: 250,
    },
    {
      adult: false,
      backdrop_path: "/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg",
      genre_ids: [16, 878, 28],
      id: 1209288,
      original_language: "en",
      original_title: "Justice League: Crisis on Infinite Earths Part Two",
      overview:
        "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?",
      popularity: 790.506,
      poster_path: "/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg",
      release_date: "2024-04-22",
      title: "Justice League: Crisis on Infinite Earths Part Two",
      video: false,
      vote_average: 6.216,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      popularity: 729.324,
      poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      release_date: "2023-07-19",
      title: "Oppenheimer",
      video: false,
      vote_average: 8.111,
      vote_count: 7811,
    },
    {
      adult: false,
      backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
      genre_ids: [10752, 28, 18],
      id: 929590,
      original_language: "en",
      original_title: "Civil War",
      overview:
        "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
      popularity: 723.121,
      poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
      release_date: "2024-04-10",
      title: "Civil War",
      video: false,
      vote_average: 7.409,
      vote_count: 485,
    },
    {
      adult: false,
      backdrop_path: "/cIztAxDn3H8JylRaJwiHHpkGe53.jpg",
      genre_ids: [10751, 35, 16],
      id: 1239146,
      original_language: "en",
      original_title: "Woody Woodpecker Goes to Camp",
      overview:
        "After getting kicked out of the forest, Woody thinks he's found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.",
      popularity: 668.689,
      poster_path: "/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg",
      release_date: "2024-04-12",
      title: "Woody Woodpecker Goes to Camp",
      video: false,
      vote_average: 6.884,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
      genre_ids: [878, 12],
      id: 438631,
      original_language: "en",
      original_title: "Dune",
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 627.288,
      poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      release_date: "2021-09-15",
      title: "Dune",
      video: false,
      vote_average: 7.79,
      vote_count: 11435,
    },
    {
      adult: false,
      backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
      genre_ids: [18, 10749],
      id: 937287,
      original_language: "en",
      original_title: "Challengers",
      overview:
        'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
      popularity: 531.851,
      poster_path: "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
      release_date: "2024-04-18",
      title: "Challengers",
      video: false,
      vote_average: 7.4,
      vote_count: 192,
    },
    {
      adult: false,
      backdrop_path: "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      genre_ids: [28, 53, 80],
      id: 560016,
      original_language: "en",
      original_title: "Monkey Man",
      overview:
        "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
      popularity: 502.284,
      poster_path: "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
      release_date: "2024-04-03",
      title: "Monkey Man",
      video: false,
      vote_average: 7.271,
      vote_count: 258,
    },
  ],
  total_pages: 229,
  total_results: 4573,
};

export const MAIN_MOVIE_VIDEOS = {
  id: 1096197,
  results: [
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Clip",
      key: "UJa1zUYegqo",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2024-02-16T16:31:54.000Z",
      id: "65d40e001d356301631e68cb",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Official Trailer",
      key: "e1k1PC0TtmE",
      site: "YouTube",
      size: 1080,
      type: "Trailer",
      official: true,
      published_at: "2023-11-30T13:02:56.000Z",
      id: "65880cfc5aba326759b95156",
    },
  ],
};
