export const NOW_PLAYING_MOVIES = {
  dates: {
    maximum: "2024-05-01",
    minimum: "2024-03-20",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
      genre_ids: [28, 27, 53],
      id: 1096197,
      original_language: "en",
      original_title: "No Way Up",
      overview:
        "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
      popularity: 2768.363,
      poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
      release_date: "2024-01-18",
      title: "No Way Up",
      video: false,
      vote_average: 6.504,
      vote_count: 484,
    },
    {
      adult: false,
      backdrop_path: "/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg",
      genre_ids: [878, 28, 18, 12],
      id: 934632,
      original_language: "en",
      original_title: "Rebel Moon — Part Two: The Scargiver",
      overview:
        "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
      popularity: 2477.048,
      poster_path: "/cxevDYdeFkiixRShbObdwAHBZry.jpg",
      release_date: "2024-04-19",
      title: "Rebel Moon — Part Two: The Scargiver",
      video: false,
      vote_average: 6.137,
      vote_count: 552,
    },
    {
      adult: false,
      backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
      genre_ids: [28, 878, 12],
      id: 823464,
      original_language: "en",
      original_title: "Godzilla x Kong: The New Empire",
      overview:
        "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
      popularity: 2372.572,
      poster_path: "/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg",
      release_date: "2024-03-27",
      title: "Godzilla x Kong: The New Empire",
      video: false,
      vote_average: 6.644,
      vote_count: 799,
    },
    {
      adult: false,
      backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
      popularity: 2020.311,
      poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
      release_date: "2024-03-02",
      title: "Kung Fu Panda 4",
      video: false,
      vote_average: 7.16,
      vote_count: 1385,
    },
    {
      adult: false,
      backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
      genre_ids: [878, 12],
      id: 693134,
      original_language: "en",
      original_title: "Dune: Part Two",
      overview:
        "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
      popularity: 1990.512,
      poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      release_date: "2024-02-27",
      title: "Dune: Part Two",
      video: false,
      vote_average: 8.263,
      vote_count: 3456,
    },
    {
      adult: false,
      backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: "en",
      original_title: "Immaculate",
      overview:
        "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
      popularity: 1542.821,
      poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
      release_date: "2024-03-20",
      title: "Immaculate",
      video: false,
      vote_average: 6.252,
      vote_count: 315,
    },
    {
      adult: false,
      backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
      genre_ids: [18, 12],
      id: 618588,
      original_language: "en",
      original_title: "Arthur the King",
      overview:
        "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
      popularity: 1308.397,
      poster_path: "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
      release_date: "2024-03-15",
      title: "Arthur the King",
      video: false,
      vote_average: 6.707,
      vote_count: 70,
    },
    {
      adult: false,
      backdrop_path: "/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg",
      genre_ids: [28, 80, 53],
      id: 1105407,
      original_language: "en",
      original_title: "Damaged",
      overview:
        "A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.",
      popularity: 1263.252,
      poster_path: "/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg",
      release_date: "2024-04-12",
      title: "Damaged",
      video: false,
      vote_average: 4.9,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
      genre_ids: [28, 14],
      id: 634492,
      original_language: "en",
      original_title: "Madame Web",
      overview:
        "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
      popularity: 947.606,
      poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
      release_date: "2024-02-14",
      title: "Madame Web",
      video: false,
      vote_average: 5.616,
      vote_count: 1162,
    },
    {
      adult: false,
      backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 929.948,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.52,
      vote_count: 1252,
    },
    {
      adult: false,
      backdrop_path: "/unCdljyU2FuUBDUcdZezeI9yaaj.jpg",
      genre_ids: [878, 9648, 53],
      id: 720321,
      original_language: "en",
      original_title: "Breathe",
      overview:
        "Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.",
      popularity: 827.058,
      poster_path: "/gPAW0a24TrkafrJQ1axEv0I3jov.jpg",
      release_date: "2024-04-04",
      title: "Breathe",
      video: false,
      vote_average: 5.042,
      vote_count: 60,
    },
    {
      adult: false,
      backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
      genre_ids: [28, 53],
      id: 984324,
      original_language: "fr",
      original_title: "Le salaire de la peur",
      overview:
        "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
      popularity: 811.937,
      poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
      release_date: "2024-03-28",
      title: "The Wages of Fear",
      video: false,
      vote_average: 5.7,
      vote_count: 202,
    },
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
      popularity: 810.306,
      poster_path: "/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
      release_date: "2024-03-19",
      title: "Late Night with the Devil",
      video: false,
      vote_average: 7.306,
      vote_count: 250,
    },
    {
      adult: false,
      backdrop_path: "/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg",
      genre_ids: [16, 878, 28],
      id: 1209288,
      original_language: "en",
      original_title: "Justice League: Crisis on Infinite Earths Part Two",
      overview:
        "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?",
      popularity: 790.506,
      poster_path: "/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg",
      release_date: "2024-04-22",
      title: "Justice League: Crisis on Infinite Earths Part Two",
      video: false,
      vote_average: 6.216,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      popularity: 729.324,
      poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      release_date: "2023-07-19",
      title: "Oppenheimer",
      video: false,
      vote_average: 8.111,
      vote_count: 7811,
    },
    {
      adult: false,
      backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
      genre_ids: [10752, 28, 18],
      id: 929590,
      original_language: "en",
      original_title: "Civil War",
      overview:
        "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
      popularity: 723.121,
      poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
      release_date: "2024-04-10",
      title: "Civil War",
      video: false,
      vote_average: 7.409,
      vote_count: 485,
    },
    {
      adult: false,
      backdrop_path: "/cIztAxDn3H8JylRaJwiHHpkGe53.jpg",
      genre_ids: [10751, 35, 16],
      id: 1239146,
      original_language: "en",
      original_title: "Woody Woodpecker Goes to Camp",
      overview:
        "After getting kicked out of the forest, Woody thinks he's found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.",
      popularity: 668.689,
      poster_path: "/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg",
      release_date: "2024-04-12",
      title: "Woody Woodpecker Goes to Camp",
      video: false,
      vote_average: 6.884,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
      genre_ids: [878, 12],
      id: 438631,
      original_language: "en",
      original_title: "Dune",
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 627.288,
      poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      release_date: "2021-09-15",
      title: "Dune",
      video: false,
      vote_average: 7.79,
      vote_count: 11435,
    },
    {
      adult: false,
      backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
      genre_ids: [18, 10749],
      id: 937287,
      original_language: "en",
      original_title: "Challengers",
      overview:
        'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
      popularity: 531.851,
      poster_path: "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
      release_date: "2024-04-18",
      title: "Challengers",
      video: false,
      vote_average: 7.4,
      vote_count: 192,
    },
    {
      adult: false,
      backdrop_path: "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      genre_ids: [28, 53, 80],
      id: 560016,
      original_language: "en",
      original_title: "Monkey Man",
      overview:
        "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
      popularity: 502.284,
      poster_path: "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
      release_date: "2024-04-03",
      title: "Monkey Man",
      video: false,
      vote_average: 7.271,
      vote_count: 258,
    },
  ],
  total_pages: 229,
  total_results: 4573,
};

export const POPULAR_MOVIES = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
      genre_ids: [28, 27, 53],
      id: 1096197,
      original_language: "en",
      original_title: "No Way Up",
      overview:
        "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
      popularity: 2011.445,
      poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
      release_date: "2024-01-18",
      title: "No Way Up",
      video: false,
      vote_average: 6.504,
      vote_count: 490,
    },
    {
      adult: false,
      backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
      genre_ids: [28, 878, 12],
      id: 823464,
      original_language: "en",
      original_title: "Godzilla x Kong: The New Empire",
      overview:
        "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
      popularity: 1898.967,
      poster_path: "/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg",
      release_date: "2024-03-27",
      title: "Godzilla x Kong: The New Empire",
      video: false,
      vote_average: 6.642,
      vote_count: 807,
    },
    {
      adult: false,
      backdrop_path: "/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg",
      genre_ids: [878, 28, 18, 12],
      id: 934632,
      original_language: "en",
      original_title: "Rebel Moon — Part Two: The Scargiver",
      overview:
        "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
      popularity: 1868.352,
      poster_path: "/cxevDYdeFkiixRShbObdwAHBZry.jpg",
      release_date: "2024-04-19",
      title: "Rebel Moon — Part Two: The Scargiver",
      video: false,
      vote_average: 6.137,
      vote_count: 562,
    },
    {
      adult: false,
      backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
      genre_ids: [878, 12],
      id: 693134,
      original_language: "en",
      original_title: "Dune: Part Two",
      overview:
        "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
      popularity: 1617.39,
      poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      release_date: "2024-02-27",
      title: "Dune: Part Two",
      video: false,
      vote_average: 8.262,
      vote_count: 3469,
    },
    {
      adult: false,
      backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
      popularity: 1578.882,
      poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
      release_date: "2024-03-02",
      title: "Kung Fu Panda 4",
      video: false,
      vote_average: 7.161,
      vote_count: 1393,
    },
    {
      adult: false,
      backdrop_path: "/jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg",
      genre_ids: [28, 878],
      id: 1094844,
      original_language: "en",
      original_title: "Ape vs. Mecha Ape",
      overview:
        "Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.",
      popularity: 1100.561,
      poster_path: "/dJaIw8OgACelojyV6YuVsOhtTLO.jpg",
      release_date: "2023-03-24",
      title: "Ape vs. Mecha Ape",
      video: false,
      vote_average: 5.1,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: "en",
      original_title: "Immaculate",
      overview:
        "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
      popularity: 1079.655,
      poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
      release_date: "2024-03-20",
      title: "Immaculate",
      video: false,
      vote_average: 6.255,
      vote_count: 319,
    },
    {
      adult: false,
      backdrop_path: "/ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg",
      genre_ids: [10752, 28, 36],
      id: 976906,
      original_language: "en",
      original_title: "Spitfire Over Berlin",
      overview:
        "August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.",
      popularity: 1039.434,
      poster_path: "/xtPPOPTad1qopK6uDe3VlYUa22o.jpg",
      release_date: "2022-05-13",
      title: "Spitfire Over Berlin",
      video: false,
      vote_average: 3.615,
      vote_count: 13,
    },
    {
      adult: false,
      backdrop_path: "/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg",
      genre_ids: [12, 28, 18],
      id: 845111,
      original_language: "fr",
      original_title: "Les trois mousquetaires : Milady",
      overview:
        "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
      popularity: 1010.828,
      poster_path: "/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg",
      release_date: "2023-12-13",
      title: "The Three Musketeers: Milady",
      video: false,
      vote_average: 6.542,
      vote_count: 353,
    },
    {
      adult: false,
      backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
      genre_ids: [18, 12],
      id: 618588,
      original_language: "en",
      original_title: "Arthur the King",
      overview:
        "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
      popularity: 936.539,
      poster_path: "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
      release_date: "2024-03-15",
      title: "Arthur the King",
      video: false,
      vote_average: 6.7,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg",
      genre_ids: [28, 80, 53],
      id: 1105407,
      original_language: "en",
      original_title: "Damaged",
      overview:
        "A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.",
      popularity: 931.866,
      poster_path: "/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg",
      release_date: "2024-04-12",
      title: "Damaged",
      video: false,
      vote_average: 4.9,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: "/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
      genre_ids: [878, 28, 14, 12],
      id: 601796,
      original_language: "ko",
      original_title: "외계+인 1부",
      overview:
        "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.",
      popularity: 813.214,
      poster_path: "/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
      release_date: "2022-07-20",
      title: "Alienoid",
      video: false,
      vote_average: 6.799,
      vote_count: 298,
    },
    {
      adult: false,
      backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
      genre_ids: [28, 14],
      id: 634492,
      original_language: "en",
      original_title: "Madame Web",
      overview:
        "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
      popularity: 790.15,
      poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
      release_date: "2024-02-14",
      title: "Madame Web",
      video: false,
      vote_average: 5.613,
      vote_count: 1168,
    },
    {
      adult: false,
      backdrop_path: "/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg",
      genre_ids: [28, 53, 10752],
      id: 784651,
      original_language: "hi",
      original_title: "फाइटर",
      overview:
        "Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.",
      popularity: 771.018,
      poster_path: "/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg",
      release_date: "2024-01-24",
      title: "Fighter",
      video: false,
      vote_average: 5.25,
      vote_count: 46,
    },
    {
      adult: false,
      backdrop_path: "/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
      genre_ids: [28, 53],
      id: 359410,
      original_language: "en",
      original_title: "Road House",
      overview:
        "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
      popularity: 755.63,
      poster_path: "/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
      release_date: "2024-03-08",
      title: "Road House",
      video: false,
      vote_average: 7.021,
      vote_count: 1623,
    },
    {
      adult: false,
      backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 745.126,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.516,
      vote_count: 1252,
    },
    {
      adult: false,
      backdrop_path: "/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg",
      genre_ids: [16, 878, 28],
      id: 1209288,
      original_language: "en",
      original_title: "Justice League: Crisis on Infinite Earths Part Two",
      overview:
        "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?",
      popularity: 743.153,
      poster_path: "/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg",
      release_date: "2024-04-22",
      title: "Justice League: Crisis on Infinite Earths Part Two",
      video: false,
      vote_average: 6.366,
      vote_count: 41,
    },
    {
      adult: false,
      backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
      genre_ids: [28, 53],
      id: 984324,
      original_language: "fr",
      original_title: "Le salaire de la peur",
      overview:
        "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
      popularity: 656.64,
      poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
      release_date: "2024-03-28",
      title: "The Wages of Fear",
      video: false,
      vote_average: 5.717,
      vote_count: 203,
    },
    {
      adult: false,
      backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
      genre_ids: [10752, 28, 18],
      id: 929590,
      original_language: "en",
      original_title: "Civil War",
      overview:
        "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
      popularity: 632.457,
      poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
      release_date: "2024-04-10",
      title: "Civil War",
      video: false,
      vote_average: 7.418,
      vote_count: 492,
    },
    {
      adult: false,
      backdrop_path: "/unCdljyU2FuUBDUcdZezeI9yaaj.jpg",
      genre_ids: [878, 9648, 53],
      id: 720321,
      original_language: "en",
      original_title: "Breathe",
      overview:
        "Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.",
      popularity: 598.62,
      poster_path: "/gPAW0a24TrkafrJQ1axEv0I3jov.jpg",
      release_date: "2024-04-04",
      title: "Breathe",
      video: false,
      vote_average: 5.0,
      vote_count: 60,
    },
  ],
  total_pages: 43878,
  total_results: 877552,
};

export const TOP_RATED_MOVIES = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 130.545,
      poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.704,
      vote_count: 26063,
    },
    {
      adult: false,
      backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 166.912,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.695,
      vote_count: 19756,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 123.706,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.577,
      vote_count: 11935,
    },
    {
      adult: false,
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 88.36,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
      video: false,
      vote_average: 8.567,
      vote_count: 15341,
    },
    {
      adult: false,
      backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 66.046,
      poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.541,
      vote_count: 8212,
    },
    {
      adult: false,
      backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 99.115,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.537,
      vote_count: 15861,
    },
    {
      adult: false,
      backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 36.127,
      poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.536,
      vote_count: 4376,
    },
    {
      adult: false,
      backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      overview:
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
      popularity: 118.156,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.515,
      vote_count: 31844,
    },
    {
      adult: false,
      backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 101.486,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.51,
      vote_count: 17473,
    },
    {
      adult: false,
      backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 128.816,
      poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.5,
      vote_count: 16765,
    },
    {
      adult: false,
      backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
      genre_ids: [16, 10749, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 80.287,
      poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.496,
      vote_count: 10940,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 299.387,
      poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.489,
      vote_count: 27001,
    },
    {
      adult: false,
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      popularity: 114.141,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-01",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.479,
      vote_count: 23322,
    },
    {
      adult: false,
      backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      popularity: 158.02,
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      release_date: "1994-06-23",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.475,
      vote_count: 26538,
    },
    {
      adult: false,
      backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
      genre_ids: [37],
      id: 429,
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      popularity: 73.34,
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      release_date: "1966-12-22",
      title: "The Good, the Bad and the Ugly",
      video: false,
      vote_average: 8.5,
      vote_count: 8232,
    },
    {
      adult: false,
      backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
      genre_ids: [18, 80],
      id: 769,
      original_language: "en",
      original_title: "GoodFellas",
      overview:
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
      popularity: 256.705,
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      release_date: "1990-09-12",
      title: "GoodFellas",
      video: false,
      vote_average: 8.466,
      vote_count: 12344,
    },
    {
      adult: false,
      backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
      genre_ids: [16, 18, 10752],
      id: 12477,
      original_language: "ja",
      original_title: "火垂るの墓",
      overview:
        "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
      popularity: 0.6,
      poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
      release_date: "1988-04-16",
      title: "Grave of the Fireflies",
      video: false,
      vote_average: 8.464,
      vote_count: 5219,
    },
    {
      adult: false,
      backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
      genre_ids: [18, 10749],
      id: 11216,
      original_language: "it",
      original_title: "Nuovo Cinema Paradiso",
      overview:
        "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
      popularity: 40.459,
      poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
      release_date: "1988-11-17",
      title: "Cinema Paradiso",
      video: false,
      vote_average: 8.453,
      vote_count: 4181,
    },
    {
      adult: false,
      backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 45.666,
      poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.453,
      vote_count: 3474,
    },
    {
      adult: false,
      backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
      genre_ids: [35, 18],
      id: 637,
      original_language: "it",
      original_title: "La vita è bella",
      overview:
        "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
      popularity: 60.498,
      poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
      release_date: "1997-12-20",
      title: "Life Is Beautiful",
      video: false,
      vote_average: 8.451,
      vote_count: 12687,
    },
  ],
  total_pages: 467,
  total_results: 9334,
};

export const UPCOMING_MOVIES = {
  dates: {
    maximum: "2024-05-22",
    minimum: "2024-05-01",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: "en",
      original_title: "Immaculate",
      overview:
        "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
      popularity: 1079.655,
      poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
      release_date: "2024-03-20",
      title: "Immaculate",
      video: false,
      vote_average: 6.255,
      vote_count: 319,
    },
    {
      adult: false,
      backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
      genre_ids: [18, 12],
      id: 618588,
      original_language: "en",
      original_title: "Arthur the King",
      overview:
        "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
      popularity: 936.539,
      poster_path: "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
      release_date: "2024-03-15",
      title: "Arthur the King",
      video: false,
      vote_average: 6.7,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
      genre_ids: [10752, 28, 18],
      id: 929590,
      original_language: "en",
      original_title: "Civil War",
      overview:
        "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
      popularity: 632.457,
      poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
      release_date: "2024-04-10",
      title: "Civil War",
      video: false,
      vote_average: 7.418,
      vote_count: 492,
    },
    {
      adult: false,
      backdrop_path: "/unCdljyU2FuUBDUcdZezeI9yaaj.jpg",
      genre_ids: [878, 9648, 53],
      id: 720321,
      original_language: "en",
      original_title: "Breathe",
      overview:
        "Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.",
      popularity: 598.62,
      poster_path: "/gPAW0a24TrkafrJQ1axEv0I3jov.jpg",
      release_date: "2024-04-04",
      title: "Breathe",
      video: false,
      vote_average: 5.0,
      vote_count: 60,
    },
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
      popularity: 598.016,
      poster_path: "/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
      release_date: "2024-03-19",
      title: "Late Night with the Devil",
      video: false,
      vote_average: 7.3,
      vote_count: 255,
    },
    {
      adult: false,
      backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      popularity: 589.967,
      poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      release_date: "2023-07-19",
      title: "Oppenheimer",
      video: false,
      vote_average: 8.1,
      vote_count: 7816,
    },
    {
      adult: false,
      backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
      genre_ids: [18, 10749],
      id: 937287,
      original_language: "en",
      original_title: "Challengers",
      overview:
        'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
      popularity: 574.924,
      poster_path: "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
      release_date: "2024-04-18",
      title: "Challengers",
      video: false,
      vote_average: 7.44,
      vote_count: 201,
    },
    {
      adult: false,
      backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 558.557,
      poster_path: "/zhyLLcwtvfNiFXDSZ2c5vOxLq2p.jpg",
      release_date: "2024-05-08",
      title: "Kingdom of the Planet of the Apes",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/kvJZLS607m1xVtEE8w95gmQ6MHE.jpg",
      genre_ids: [27],
      id: 1015303,
      original_language: "en",
      original_title: "Elevator Game",
      overview:
        "Follows socially awkward teenager Ryan, who discovers that the night his sister disappeared she had played ‘The Elevator Game’ — a ritual conducted in an elevator in which players attempt to travel to another dimension using a set of rules that can be found online. Ignoring warnings, he resolves to follow and find her.",
      popularity: 456.908,
      poster_path: "/a4Zb13jow8RqJkYFgCUSdmzJCWq.jpg",
      release_date: "2023-07-12",
      title: "Elevator Game",
      video: false,
      vote_average: 4.663,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      genre_ids: [28, 53, 80],
      id: 560016,
      original_language: "en",
      original_title: "Monkey Man",
      overview:
        "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
      popularity: 410.326,
      poster_path: "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
      release_date: "2024-04-03",
      title: "Monkey Man",
      video: false,
      vote_average: 7.245,
      vote_count: 263,
    },
    {
      adult: false,
      backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
      genre_ids: [28, 53, 10752],
      id: 969492,
      original_language: "en",
      original_title: "Land of Bad",
      overview:
        "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
      popularity: 407.572,
      poster_path: "/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg",
      release_date: "2024-01-25",
      title: "Land of Bad",
      video: false,
      vote_average: 7.263,
      vote_count: 664,
    },
    {
      adult: false,
      backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
      genre_ids: [27, 53, 35],
      id: 1111873,
      original_language: "en",
      original_title: "Abigail",
      overview:
        "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
      popularity: 372.884,
      poster_path: "/5Uq8P6MPj9Ppsns5t82AiCiUaWE.jpg",
      release_date: "2024-04-18",
      title: "Abigail",
      video: false,
      vote_average: 6.9,
      vote_count: 77,
    },
    {
      adult: false,
      backdrop_path: "/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg",
      genre_ids: [80, 10749, 53],
      id: 948549,
      original_language: "en",
      original_title: "Love Lies Bleeding",
      overview:
        "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
      popularity: 340.777,
      poster_path: "/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg",
      release_date: "2024-03-08",
      title: "Love Lies Bleeding",
      video: false,
      vote_average: 6.989,
      vote_count: 94,
    },
    {
      adult: false,
      backdrop_path: "/v5XyXZe8FADw8iHupB4L7QOAwH9.jpg",
      genre_ids: [16, 35, 10751],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      popularity: 331.073,
      poster_path: "/zK2sFxZcelHJRPVr242rxy5VK4T.jpg",
      release_date: "2024-04-30",
      title: "The Garfield Movie",
      video: false,
      vote_average: 3.2,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/2rjI2uXmjitMAaXVO21r9ao7v2j.jpg",
      genre_ids: [28, 35, 12],
      id: 746036,
      original_language: "en",
      original_title: "The Fall Guy",
      overview:
        "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
      popularity: 300.819,
      poster_path: "/e7olqFmzcIX5c23kX4zSmLPJi8c.jpg",
      release_date: "2024-04-24",
      title: "The Fall Guy",
      video: false,
      vote_average: 7.93,
      vote_count: 43,
    },
    {
      adult: false,
      backdrop_path: "/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg",
      genre_ids: [10749, 35],
      id: 1072790,
      original_language: "en",
      original_title: "Anyone But You",
      overview:
        "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
      popularity: 294.892,
      poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
      release_date: "2023-12-21",
      title: "Anyone But You",
      video: false,
      vote_average: 7.085,
      vote_count: 1414,
    },
    {
      adult: false,
      backdrop_path: "/k0ucFBBgSDTXYU8fVHXJyjAuIIe.jpg",
      genre_ids: [27],
      id: 1063879,
      original_language: "fr",
      original_title: "Vermines",
      overview:
        "Residents of a rundown French apartment building battle against an army of deadly, rapidly reproducing spiders.",
      popularity: 252.4,
      poster_path: "/dY98PkUAbIGUUg0FhXEcOkbzHIZ.jpg",
      release_date: "2023-12-27",
      title: "Infested",
      video: false,
      vote_average: 7.235,
      vote_count: 132,
    },
    {
      adult: false,
      backdrop_path: "/kSdIVZu7Cv60o9hTbKBzcTrbMX8.jpg",
      genre_ids: [28, 53],
      id: 984249,
      original_language: "en",
      original_title: "Ruthless",
      overview:
        "A high school coach, whose teenage daughter was murdered, takes matters into his own hands by going after the men who kidnap his students for their sex trafficking operation.",
      popularity: 205.791,
      poster_path: "/4ndp1pnHWRuiZLNpFJvO4Kh6Tav.jpg",
      release_date: "2023-12-14",
      title: "Ruthless",
      video: false,
      vote_average: 6.5,
      vote_count: 55,
    },
    {
      adult: false,
      backdrop_path: "/otfoeC96neoOdA4HqsX06OWuzE9.jpg",
      genre_ids: [27, 53],
      id: 719221,
      original_language: "en",
      original_title: "Tarot",
      overview:
        "When a group of friends recklessly violates the sacred rule of Tarot readings they unknowingly unleash an unspeakable evil trapped within the cursed cards. One by one, they come face to face with fate and end up in a race against death.",
      popularity: 164.69,
      poster_path: "/gAEUXC37vl1SnM7PXsHTF23I2vq.jpg",
      release_date: "2024-05-01",
      title: "Tarot",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/1ZSKH5GGFlM8M32K34GMdaNS2Ew.jpg",
      genre_ids: [10402, 36, 18],
      id: 802219,
      original_language: "en",
      original_title: "Bob Marley: One Love",
      overview:
        "Jamaican singer-songwriter Bob Marley overcomes adversity to become the most famous reggae musician in the world.",
      popularity: 145.635,
      poster_path: "/n0GVTNJvhUlJ1Mj73JHZBTHVFuc.jpg",
      release_date: "2024-02-14",
      title: "Bob Marley: One Love",
      video: false,
      vote_average: 7.0,
      vote_count: 516,
    },
  ],
  total_pages: 57,
  total_results: 1124,
};

export const ON_THE_AIR_SHOWS = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/butPVWgcbtAjL9Z7jU7Xj1KA8KD.jpg",
      genre_ids: [10767, 35],
      id: 22980,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Watch What Happens Live with Andy Cohen",
      overview:
        "Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.",
      popularity: 4759.765,
      poster_path: "/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg",
      first_air_date: "2009-07-16",
      name: "Watch What Happens Live with Andy Cohen",
      vote_average: 4.99,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: "/h0y3OzHzG4yNvn8u3Za6ByH8lrQ.jpg",
      genre_ids: [18, 10766],
      id: 45789,
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Sturm der Liebe",
      overview:
        "These are the stories of relationships taking place in the fictional five-star hotel Fürstenhof, located in Feldkirchen-Westerham near Rosenheim with the plot revolving around members of the family room area, the hotel owners, and employees.",
      popularity: 4452.014,
      poster_path: "/9oZjOh3Va3FsiLGouhSogFsBX9G.jpg",
      first_air_date: "2005-09-26",
      name: "Sturm der Liebe",
      vote_average: 5.9,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: "/hib8MpBPU7GdluS38htXCF4uw0c.jpg",
      genre_ids: [80, 18, 9648],
      id: 2734,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Law \u0026 Order: Special Victims Unit",
      overview:
        "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
      popularity: 3904.089,
      poster_path: "/onmSVwYsPMYtO8OjLdjS8FfRNKb.jpg",
      first_air_date: "1999-09-20",
      name: "Law \u0026 Order: Special Victims Unit",
      vote_average: 7.942,
      vote_count: 3626,
    },
    {
      adult: false,
      backdrop_path: "/nmg2lY4QuyXQrAnrC2lRblK5rT6.jpg",
      genre_ids: [18],
      id: 1416,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Grey's Anatomy",
      overview:
        "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
      popularity: 3848.108,
      poster_path: "/jcEl8SISNfGdlQFwLzeEtsjDvpw.jpg",
      first_air_date: "2005-03-27",
      name: "Grey's Anatomy",
      vote_average: 8.242,
      vote_count: 9920,
    },
    {
      adult: false,
      backdrop_path: "/lhdUwhInXu31qHm65jwBAlpTp8P.jpg",
      genre_ids: [10767],
      id: 82873,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Kelly Clarkson Show",
      overview:
        "Kelly Clarkson presents the biggest newsmakers and names in film, television and music; as well as emerging new talent and everyday people who are beacons of hope in their communities.",
      popularity: 3648.46,
      poster_path: "/9Gg1oM8Us8gCS5aJA8e0ZRuIHnf.jpg",
      first_air_date: "2019-09-09",
      name: "The Kelly Clarkson Show",
      vote_average: 6.274,
      vote_count: 42,
    },
    {
      adult: false,
      backdrop_path: "/mDK2cWErxVyHwnSOCCiXBcIjS3K.jpg",
      genre_ids: [10763, 35],
      id: 2224,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Daily Show",
      overview:
        "The World's Fakest News Team tackle the biggest stories in news, politics and pop culture.",
      popularity: 3323.803,
      poster_path: "/ixcfyK7it6FjRM36Te4OdblAq4X.jpg",
      first_air_date: "1996-07-22",
      name: "The Daily Show",
      vote_average: 6.3,
      vote_count: 502,
    },
    {
      adult: false,
      backdrop_path: "/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg",
      genre_ids: [35, 10767],
      id: 59941,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Tonight Show Starring Jimmy Fallon",
      overview:
        "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
      popularity: 3300.087,
      poster_path: "/g4amxJvtpnY79J77xeamnAEUO8r.jpg",
      first_air_date: "2014-02-17",
      name: "The Tonight Show Starring Jimmy Fallon",
      vote_average: 5.848,
      vote_count: 302,
    },
    {
      adult: false,
      backdrop_path: "/mUid3rbVigsDB3dgUUC04fYPrDB.jpg",
      genre_ids: [10764],
      id: 137228,
      origin_country: ["US"],
      original_language: "es",
      original_name: "La Casa de los Famosos",
      overview: "",
      popularity: 2876.954,
      poster_path: "/fxCgd9KZt06CxMDVztPEuV8F3b9.jpg",
      first_air_date: "2021-08-24",
      name: "La Casa de los Famosos",
      vote_average: 5.071,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/mpcrV6RKlXxTsOCt7K70pJzNzNI.jpg",
      genre_ids: [10767],
      id: 204746,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Jennifer Hudson Show",
      overview:
        "Talented entertainer and newly-minted EGOT Jennifer Hudson takes on the daytime talk show landscape.",
      popularity: 2806.317,
      poster_path: "/6VBNeo8XG90sNKWYQ0yTEmVBXHJ.jpg",
      first_air_date: "2022-09-12",
      name: "The Jennifer Hudson Show",
      vote_average: 7.2,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg",
      genre_ids: [10767, 35],
      id: 61818,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Late Night with Seth Meyers",
      overview:
        'Seth Meyers, who is "Saturday Night Live’s" longest serving anchor on the show’s wildly popular "Weekend Update," takes over as host of NBC’s "Late Night" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for "SNL," Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from "SNL" to his new post at "Late Night," as Jimmy Fallon moves to "The Tonight Show".',
      popularity: 2755.172,
      poster_path: "/g6MrJxNaHYGYU7Sxo72e5B8gKOV.jpg",
      first_air_date: "2014-02-25",
      name: "Late Night with Seth Meyers",
      vote_average: 5.6,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: "/eBV4wZ3RFRsZyZ74kP7FfiBTKp1.jpg",
      genre_ids: [35, 10764],
      id: 31248,
      origin_country: ["PH"],
      original_language: "tl",
      original_name: "It's Showtime",
      overview:
        "A Philippine noontime musical and party variety show. What began as a search for the country’s most entertaining acts evolves into a hit variety program thriving on spontaneity and animated conversations while drawing talents from all walks of life.",
      popularity: 2656.19,
      poster_path: "/nKxXaAIO2ljugKhKFYQ8LmIJ1x7.jpg",
      first_air_date: "2009-10-24",
      name: "It's Showtime",
      vote_average: 7.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/uCY1j1YqfDWRbbS7hJwd9szX1sJ.jpg",
      genre_ids: [10766, 18, 35],
      id: 237480,
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "No Rancho Fundo",
      overview: "",
      popularity: 2603.805,
      poster_path: "/eONkvEahSQJan1HTzWJKjvaMe29.jpg",
      first_air_date: "2024-04-15",
      name: "No Rancho Fundo",
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/rj3jBAZwPiOgkwAy1205MAgLahj.jpg",
      genre_ids: [10766],
      id: 81329,
      origin_country: ["FR"],
      original_language: "fr",
      original_name: "Un si grand soleil",
      overview:
        "Claire is surprised when she gets arrested for the murder of her childhood friend after she returns to Montpellier.",
      popularity: 2549.4,
      poster_path: "/t6jVlbPMtZOJoAOfeoR4yQmnjXM.jpg",
      first_air_date: "2018-08-27",
      name: "Chronicles of the Sun",
      vote_average: 7.151,
      vote_count: 73,
    },
    {
      adult: false,
      backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      genre_ids: [35, 10767],
      id: 63770,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Show with Stephen Colbert",
      overview:
        "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.must watch",
      popularity: 2491.779,
      poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      first_air_date: "2015-09-08",
      name: "The Late Show with Stephen Colbert",
      vote_average: 6.541,
      vote_count: 257,
    },
    {
      adult: false,
      backdrop_path: "/s92ZvqE4gWOrZq60AKvhgZZxDY4.jpg",
      genre_ids: [10764],
      id: 240909,
      origin_country: ["CO"],
      original_language: "es",
      original_name: "La Casa de los Famosos Colombia",
      overview: "",
      popularity: 2457.188,
      poster_path: "/lCn94cscNlFToXIbIWRSGBqb20Q.jpg",
      first_air_date: "2024-02-11",
      name: "La Casa de los Famosos Colombia",
      vote_average: 6.357,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: "/lN9YTWjXXJ62hJLsdGAjp5z76JU.jpg",
      genre_ids: [10766, 18],
      id: 231418,
      origin_country: ["ES"],
      original_language: "es",
      original_name: "Salón de té La Moderna",
      overview: "",
      popularity: 2363.873,
      poster_path: "/eRB6yMg6FyvjlxEZYu0ZEUdy1Nd.jpg",
      first_air_date: "2023-09-27",
      name: "Salón de té La Moderna",
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/eWF3oRyL4QWaidN9F4uvM7cBJUV.jpg",
      genre_ids: [10766],
      id: 206559,
      origin_country: ["ZA"],
      original_language: "af",
      original_name: "Binnelanders",
      overview:
        "A South African Afrikaans soap opera. It is set in and around the fictional private hospital, Binneland Kliniek, in Pretoria, and the storyline follows the trials, trauma and tribulations of the staff and patients of the hospital.",
      popularity: 2348.233,
      poster_path: "/v9nGSRx5lFz6KEgfmgHJMSgaARC.jpg",
      first_air_date: "2005-10-13",
      name: "Binnelanders",
      vote_average: 5.569,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
      genre_ids: [10763],
      id: 94722,
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Tagesschau",
      overview:
        "German daily news program, the oldest still existing program on German television.",
      popularity: 2315.027,
      poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
      first_air_date: "1952-12-26",
      name: "Tagesschau",
      vote_average: 6.832,
      vote_count: 199,
    },
    {
      adult: false,
      backdrop_path: "/bEKRyT7WN5TjFKv0JTWI2cyNlak.jpg",
      genre_ids: [10766, 18],
      id: 223365,
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Renascer",
      overview:
        "After making a pact with Jequitibá, José Inocêncio becomes a mythical figure, known as the most successful cocoa farmer in the region. While still young, he wins the heart of Maria Santa. Their intense passion results in four children: José Augusto, José Bento, José Venâncio, and the youngest, João Pedro, who never had the opportunity to know his mother, as she dies while giving birth to him. This tragedy fuels José Inocêncio’s anger, blaming João Pedro for the loss of his great love. Throughout their lives, indifference and resentment mark the relationship between the father and his youngest son. As if the past weren’t enough, years later, the arrival of the mysterious Mariana puts all these emotions to the test when both father and son fall in love with the same woman. This situation reawakens feelings that were either dormant or previously unknown to them.",
      popularity: 2212.7,
      poster_path: "/kUWvvMkNIf21UUDmHjYw55v6o7C.jpg",
      first_air_date: "2024-01-22",
      name: "Rebirth",
      vote_average: 7.8,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/yWVqYVOUcS6vu22v4BPXKJW10m5.jpg",
      genre_ids: [10764, 10751],
      id: 206679,
      origin_country: ["CZ"],
      original_language: "cs",
      original_name: "Na lovu",
      overview:
        "Na Lovu is a Czech game-show, based on the license of the popular global format The Chase. A heart-racing quiz show where four competitors must pit their wits and face off against Lovec (the Chaser), a ruthless quiz genius determined to stop them from winning cash prizes.",
      popularity: 2192.275,
      poster_path: "/udJ1wVuOwFg1q6UBcQGwcpcdIYF.jpg",
      first_air_date: "2021-08-16",
      name: "Na lovu",
      vote_average: 8.0,
      vote_count: 2,
    },
  ],
  total_pages: 65,
  total_results: 1285,
};

export const AIRING_TODAY_SHOWS = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/butPVWgcbtAjL9Z7jU7Xj1KA8KD.jpg",
      genre_ids: [10767, 35],
      id: 22980,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Watch What Happens Live with Andy Cohen",
      overview:
        "Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.",
      popularity: 4759.765,
      poster_path: "/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg",
      first_air_date: "2009-07-16",
      name: "Watch What Happens Live with Andy Cohen",
      vote_average: 5.092,
      vote_count: 49,
    },
    {
      adult: false,
      backdrop_path: "/h0y3OzHzG4yNvn8u3Za6ByH8lrQ.jpg",
      genre_ids: [18, 10766],
      id: 45789,
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Sturm der Liebe",
      overview:
        "These are the stories of relationships taking place in the fictional five-star hotel Fürstenhof, located in Feldkirchen-Westerham near Rosenheim with the plot revolving around members of the family room area, the hotel owners, and employees.",
      popularity: 4452.014,
      poster_path: "/9oZjOh3Va3FsiLGouhSogFsBX9G.jpg",
      first_air_date: "2005-09-26",
      name: "Sturm der Liebe",
      vote_average: 5.9,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: "/lhdUwhInXu31qHm65jwBAlpTp8P.jpg",
      genre_ids: [10767],
      id: 82873,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Kelly Clarkson Show",
      overview:
        "Kelly Clarkson presents the biggest newsmakers and names in film, television and music; as well as emerging new talent and everyday people who are beacons of hope in their communities.",
      popularity: 3648.46,
      poster_path: "/9Gg1oM8Us8gCS5aJA8e0ZRuIHnf.jpg",
      first_air_date: "2019-09-09",
      name: "The Kelly Clarkson Show",
      vote_average: 6.274,
      vote_count: 42,
    },
    {
      adult: false,
      backdrop_path: "/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg",
      genre_ids: [35, 10767],
      id: 59941,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Tonight Show Starring Jimmy Fallon",
      overview:
        "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
      popularity: 3300.087,
      poster_path: "/g4amxJvtpnY79J77xeamnAEUO8r.jpg",
      first_air_date: "2014-02-17",
      name: "The Tonight Show Starring Jimmy Fallon",
      vote_average: 5.848,
      vote_count: 302,
    },
    {
      adult: false,
      backdrop_path: "/mUid3rbVigsDB3dgUUC04fYPrDB.jpg",
      genre_ids: [10764],
      id: 137228,
      origin_country: ["US"],
      original_language: "es",
      original_name: "La Casa de los Famosos",
      overview: "",
      popularity: 2876.954,
      poster_path: "/fxCgd9KZt06CxMDVztPEuV8F3b9.jpg",
      first_air_date: "2021-08-24",
      name: "La Casa de los Famosos",
      vote_average: 5.7,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/mpcrV6RKlXxTsOCt7K70pJzNzNI.jpg",
      genre_ids: [10767],
      id: 204746,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Jennifer Hudson Show",
      overview:
        "Talented entertainer and newly-minted EGOT Jennifer Hudson takes on the daytime talk show landscape.",
      popularity: 2806.317,
      poster_path: "/6VBNeo8XG90sNKWYQ0yTEmVBXHJ.jpg",
      first_air_date: "2022-09-12",
      name: "The Jennifer Hudson Show",
      vote_average: 7.2,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg",
      genre_ids: [10767, 35],
      id: 61818,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Late Night with Seth Meyers",
      overview:
        'Seth Meyers, who is "Saturday Night Live’s" longest serving anchor on the show’s wildly popular "Weekend Update," takes over as host of NBC’s "Late Night" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for "SNL," Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from "SNL" to his new post at "Late Night," as Jimmy Fallon moves to "The Tonight Show".',
      popularity: 2755.172,
      poster_path: "/g6MrJxNaHYGYU7Sxo72e5B8gKOV.jpg",
      first_air_date: "2014-02-25",
      name: "Late Night with Seth Meyers",
      vote_average: 5.6,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: "/eBV4wZ3RFRsZyZ74kP7FfiBTKp1.jpg",
      genre_ids: [35, 10764],
      id: 31248,
      origin_country: ["PH"],
      original_language: "tl",
      original_name: "It's Showtime",
      overview:
        "A Philippine noontime musical and party variety show. What began as a search for the country’s most entertaining acts evolves into a hit variety program thriving on spontaneity and animated conversations while drawing talents from all walks of life.",
      popularity: 2656.19,
      poster_path: "/nKxXaAIO2ljugKhKFYQ8LmIJ1x7.jpg",
      first_air_date: "2009-10-24",
      name: "It's Showtime",
      vote_average: 7.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/uCY1j1YqfDWRbbS7hJwd9szX1sJ.jpg",
      genre_ids: [10766, 18, 35],
      id: 237480,
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "No Rancho Fundo",
      overview: "",
      popularity: 2603.805,
      poster_path: "/eONkvEahSQJan1HTzWJKjvaMe29.jpg",
      first_air_date: "2024-04-15",
      name: "No Rancho Fundo",
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/rj3jBAZwPiOgkwAy1205MAgLahj.jpg",
      genre_ids: [10766],
      id: 81329,
      origin_country: ["FR"],
      original_language: "fr",
      original_name: "Un si grand soleil",
      overview:
        "Claire is surprised when she gets arrested for the murder of her childhood friend after she returns to Montpellier.",
      popularity: 2549.4,
      poster_path: "/t6jVlbPMtZOJoAOfeoR4yQmnjXM.jpg",
      first_air_date: "2018-08-27",
      name: "Chronicles of the Sun",
      vote_average: 7.151,
      vote_count: 73,
    },
    {
      adult: false,
      backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      genre_ids: [35, 10767],
      id: 63770,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Late Show with Stephen Colbert",
      overview:
        "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.must watch",
      popularity: 2491.779,
      poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      first_air_date: "2015-09-08",
      name: "The Late Show with Stephen Colbert",
      vote_average: 6.541,
      vote_count: 257,
    },
    {
      adult: false,
      backdrop_path: "/s92ZvqE4gWOrZq60AKvhgZZxDY4.jpg",
      genre_ids: [10764],
      id: 240909,
      origin_country: ["CO"],
      original_language: "es",
      original_name: "La Casa de los Famosos Colombia",
      overview: "",
      popularity: 2457.188,
      poster_path: "/lCn94cscNlFToXIbIWRSGBqb20Q.jpg",
      first_air_date: "2024-02-11",
      name: "La Casa de los Famosos Colombia",
      vote_average: 6.357,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: "/lN9YTWjXXJ62hJLsdGAjp5z76JU.jpg",
      genre_ids: [10766, 18],
      id: 231418,
      origin_country: ["ES"],
      original_language: "es",
      original_name: "Salón de té La Moderna",
      overview: "",
      popularity: 2363.873,
      poster_path: "/eRB6yMg6FyvjlxEZYu0ZEUdy1Nd.jpg",
      first_air_date: "2023-09-27",
      name: "Salón de té La Moderna",
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/eWF3oRyL4QWaidN9F4uvM7cBJUV.jpg",
      genre_ids: [10766],
      id: 206559,
      origin_country: ["ZA"],
      original_language: "af",
      original_name: "Binnelanders",
      overview:
        "A South African Afrikaans soap opera. It is set in and around the fictional private hospital, Binneland Kliniek, in Pretoria, and the storyline follows the trials, trauma and tribulations of the staff and patients of the hospital.",
      popularity: 2348.233,
      poster_path: "/v9nGSRx5lFz6KEgfmgHJMSgaARC.jpg",
      first_air_date: "2005-10-13",
      name: "Binnelanders",
      vote_average: 5.569,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
      genre_ids: [10763],
      id: 94722,
      origin_country: ["DE"],
      original_language: "de",
      original_name: "Tagesschau",
      overview:
        "German daily news program, the oldest still existing program on German television.",
      popularity: 2315.027,
      poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
      first_air_date: "1952-12-26",
      name: "Tagesschau",
      vote_average: 6.832,
      vote_count: 199,
    },
    {
      adult: false,
      backdrop_path: "/bEKRyT7WN5TjFKv0JTWI2cyNlak.jpg",
      genre_ids: [10766, 18],
      id: 223365,
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Renascer",
      overview:
        "After making a pact with Jequitibá, José Inocêncio becomes a mythical figure, known as the most successful cocoa farmer in the region. While still young, he wins the heart of Maria Santa. Their intense passion results in four children: José Augusto, José Bento, José Venâncio, and the youngest, João Pedro, who never had the opportunity to know his mother, as she dies while giving birth to him. This tragedy fuels José Inocêncio’s anger, blaming João Pedro for the loss of his great love. Throughout their lives, indifference and resentment mark the relationship between the father and his youngest son. As if the past weren’t enough, years later, the arrival of the mysterious Mariana puts all these emotions to the test when both father and son fall in love with the same woman. This situation reawakens feelings that were either dormant or previously unknown to them.",
      popularity: 2212.7,
      poster_path: "/kUWvvMkNIf21UUDmHjYw55v6o7C.jpg",
      first_air_date: "2024-01-22",
      name: "Rebirth",
      vote_average: 7.8,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: "/yWVqYVOUcS6vu22v4BPXKJW10m5.jpg",
      genre_ids: [10764, 10751],
      id: 206679,
      origin_country: ["CZ"],
      original_language: "cs",
      original_name: "Na lovu",
      overview:
        "Na Lovu is a Czech game-show, based on the license of the popular global format The Chase. A heart-racing quiz show where four competitors must pit their wits and face off against Lovec (the Chaser), a ruthless quiz genius determined to stop them from winning cash prizes.",
      popularity: 2192.275,
      poster_path: "/udJ1wVuOwFg1q6UBcQGwcpcdIYF.jpg",
      first_air_date: "2021-08-16",
      name: "Na lovu",
      vote_average: 8.0,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/yYNa1nqvNK94xZz3eKyfvZdAvPi.jpg",
      genre_ids: [10766, 18],
      id: 112470,
      origin_country: ["FR"],
      original_language: "fr",
      original_name: "Ici tout commence",
      overview: "",
      popularity: 2101.434,
      poster_path: "/yuTHx38jpogXovMhqNatvozigMJ.jpg",
      first_air_date: "2020-11-02",
      name: "Here it all begins",
      vote_average: 7.1,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/hpZ5VJP1MvQjuFUMORuAoDFAH30.jpg",
      genre_ids: [35, 10766, 10759],
      id: 222289,
      origin_country: ["BR"],
      original_language: "pt",
      original_name: "Família é Tudo",
      overview: "",
      popularity: 2089.115,
      poster_path: "/tDbJuSfVhf3ZnxiJrXlXEALyAz5.jpg",
      first_air_date: "2024-03-04",
      name: "Família é Tudo",
      vote_average: 3.5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/y1e4wd1e60vNitKfNu3uva9I5wJ.jpg",
      genre_ids: [10767],
      id: 210081,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Sherri",
      overview:
        'Sherri Shepherd, actress, comic, and Emmy Award-winning longtime co-host of "The View", appears before a live audience with a daily dose of pop culture, comedy, conversations, and daytime talk staples, including celebrity and human interest interviews;',
      popularity: 2074.17,
      poster_path: "/7qcRQY4nSGrQ0lMMDV1c0dKKOoc.jpg",
      first_air_date: "2022-09-12",
      name: "Sherri",
      vote_average: 4.8,
      vote_count: 6,
    },
  ],
  total_pages: 18,
  total_results: 356,
};

export const MAIN_MOVIE_VIDEOS = {
  id: 1096197,
  results: [
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Clip",
      key: "UJa1zUYegqo",
      site: "YouTube",
      size: 1080,
      type: "Clip",
      official: true,
      published_at: "2024-02-16T16:31:54.000Z",
      id: "65d40e001d356301631e68cb",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Official Trailer",
      key: "e1k1PC0TtmE",
      site: "YouTube",
      size: 1080,
      type: "Trailer",
      official: true,
      published_at: "2023-11-30T13:02:56.000Z",
      id: "65880cfc5aba326759b95156",
    },
  ],
};
